
import {IPiece} from './model'

export const pieces:IPiece[] = [
    {
        name:'blackRook_1',
        location:'',
        src: 'assets/BlackRook.png',
        moved:false,
        color:'black',
        type:'rook',
        userID:'',
    },
    {
        name:'blackKnight_1',
        location:'',
        src: 'assets/BlackKnight.png',
        moved:false,
        color:'black',
        type:'knight',
        userID:'',
    },
    {
        name:'blackBishop_1',
        location:'',
        src: 'assets/BlackBishop.png',
        moved:false,
        color:'black',
        type:'bishop',
        userID:'',
    },
    {
        name:'blackKing',
        location:'',
        src: 'assets/BlackKing.png',
        moved:false,
        color:'black',
        type:'king',
        userID:'',
    },
    {
        name:'blackQueen',
        location:'',
        src: 'assets/BlackQueen.png',
        moved:false,
        color:'black',
        type:'queen',
        userID:'',
    },
    {
        name:'blackBishop_2',
        location:'',
        src: 'assets/BlackBishop.png',
        moved:false,
        color:'black',
        type:'bishop',
        userID:'',
    },
    {
        name:'blackKnight_2',
        location:'',
        src: 'assets/BlackKnight.png',
        moved:false,
        color:'black',
        type:'knight',
        userID:'',
    },
    {
        name:'blackRook_2',
        location:'',
        src: 'assets/BlackRook.png',
        moved:false,
        color:'black',
        type:'rook',
        userID:'',
    },
    {
        name:'blackPawn_1',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'blackPawn_2',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'blackPawn_3',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'blackPawn_4',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'blackPawn_5',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'blackPawn_6',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'blackPawn_7',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'blackPawn_8',
        location:'',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_1',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_2',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_3',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_4',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_5',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_6',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_7',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whitePawn_8',
        location:'',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
        userID:'',
    },
    {
        name:'whiteRook_1',
        location:'',
        src: 'assets/WhiteRook.png',
        moved:false,
        color:'white',
        type:'rook',
        userID:'',
    },
    {
        name:'whiteKnight_1',
        location:'',
        src: 'assets/WhiteKnight.png',
        moved:false,
        color:'white',
        type:'knight',
        userID:'',
    },
    {
        name:'whiteBishop_1',
        location:'',
        src: 'assets/WhiteBishop.png',
        moved:false,
        color:'white',
        type:'bishop',
        userID:'',
    },
    {
        name:'whiteKing',
        location:'',
        src: 'assets/WhiteKing.png',
        moved:false,
        color:'white',
        type:'king',
        userID:'',
    },
    {
        name:'whiteQueen',
        location:'',
        src: 'assets/WhiteQueen.png',
        moved:false,
        color:'white',
        type:'queen',
        userID:'',
    },
    {
        name:'whiteBishop_2',
        location:'',
        src: 'assets/WhiteBishop.png',
        moved:false,
        color:'white',
        type:'bishop',
        userID:'',
    },
    {
        name:'whiteKnight_2',
        location:'',
        src: 'assets/WhiteKnight.png',
        moved:false,
        color:'white',
        type:'knight',
        userID:'',
    },
    {
        name:'whiteRook_2',
        location:'',
        src: 'assets/WhiteRook.png',
        moved:false,
        color:'white',
        type:'rook',
        userID:'',
    },
]