import * as path from 'path';
import * as url from 'url';
// const __filename = url.parse(import.meta.url);
// const __dirname = path.dirname(String(__filename));

import {IPiece} from './model'

export const pieces:IPiece[] = [
    {
        name:'blackRook_1',
        location:'a8',
        src: 'assets/BlackRook.png',
        moved:false,
        color:'black',
        type:'rook',
    },
    {
        name:'blackKnight_1',
        location:'b8',
        src: 'assets/BlackKnight.png',
        moved:false,
        color:'black',
        type:'knight',
    },
    {
        name:'blackBishop_1',
        location:'c8',
        src: 'assets/BlackBishop.png',
        moved:false,
        color:'black',
        type:'bishop',
    },
    {
        name:'blackKing',
        location:'d8',
        src: 'assets/BlackKing.png',
        moved:false,
        color:'black',
        type:'king',
    },
    {
        name:'blackQueen',
        location:'e8',
        src: 'assets/BlackQueen.png',
        moved:false,
        color:'black',
        type:'queen',
    },
    {
        name:'blackBishop_2',
        location:'f8',
        src: 'assets/BlackBishop.png',
        moved:false,
        color:'black',
        type:'bishop',
    },
    {
        name:'blackKnight_2',
        location:'g8',
        src: 'assets/BlackKnight.png',
        moved:false,
        color:'black',
        type:'knight',
    },
    {
        name:'blackRook_2',
        location:'h8',
        src: 'assets/BlackRook.png',
        moved:false,
        color:'black',
        type:'rook',
    },
    {
        name:'blackPawn_1',
        location:'a7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'blackPawn_2',
        location:'b7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'blackPawn_3',
        location:'c7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'blackPawn_4',
        location:'d7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'blackPawn_5',
        location:'e7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'blackPawn_6',
        location:'f7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'blackPawn_7',
        location:'g7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'blackPawn_8',
        location:'h7',
        src: 'assets/BlackPawn.png',
        moved:false,
        color:'black',
        type:'pawn',
    },
    {
        name:'whitePawn_1',
        location:'a2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whitePawn_2',
        location:'b2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whitePawn_3',
        location:'c2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whitePawn_4',
        location:'d2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whitePawn_5',
        location:'e2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whitePawn_6',
        location:'f2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whitePawn_7',
        location:'g2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whitePawn_8',
        location:'h2',
        src: 'assets/WhitePawn.png',
        moved:false,
        color:'white',
        type:'pawn',
    },
    {
        name:'whiteRook_1',
        location:'a1',
        src: 'assets/WhiteRook.png',
        moved:false,
        color:'white',
        type:'rook',
    },
    {
        name:'whiteKnight_1',
        location:'b1',
        src: 'assets/WhiteKnight.png',
        moved:false,
        color:'white',
        type:'knight',
    },
    {
        name:'whiteBishop_1',
        location:'c1',
        src: 'assets/WhiteBishop.png',
        moved:false,
        color:'white',
        type:'bishop',
    },
    {
        name:'whiteKing',
        location:'d1',
        src: 'assets/WhiteKing.png',
        moved:false,
        color:'white',
        type:'king',
    },
    {
        name:'whiteQueen',
        location:'e1',
        src: 'assets/WhiteQueen.png',
        moved:false,
        color:'white',
        type:'queen',
    },
    {
        name:'whiteBishop_2',
        location:'f1',
        src: 'assets/WhiteBishop.png',
        moved:false,
        color:'white',
        type:'bishop',
    },
    {
        name:'whiteKnight_2',
        location:'g1',
        src: 'assets/WhiteKnight.png',
        moved:false,
        color:'white',
        type:'knight',
    },
    {
        name:'whiteRook_2',
        location:'h1',
        src: 'assets/WhiteRook.png',
        moved:false,
        color:'white',
        type:'rook',
    },
]